spring:
  datasource:
    url: jdbc:h2:mem:sa
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true
api:
  endpoint:
    base-url: /api/v1

server:
  port: 80