spring:
  profiles:
    active: development # ENV: SPRING_PROFILES_ACTIVE=production
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

api:
  endpoint:
    base-url: /api/v1

server:
  port: 80
